title: The Bandar Co.
description: "B.Com Grad"
url: "https://thebandar.co.in"
baseurl: ""

share: true
search: true

owner:
  name: Amay
  avatar: avatar.png
  favicon: favicon.ico
  info: Portfolio, blog and more
  email: "amaydeepp12510@gmail.com"
  whatsapp: "7588643764"
  instagram: "chillbandar"
  linkedin: "amay-deep-34158b229"
  github: "XiaoPongo"

exclude_from_search:
  - assets/
  - css/
  - js/
  - images/
  - 404.html
  - search.html
  - tags/
  - categories/
  - journal/
  - projects/project*/
  - *.css
  - *.js
  - *.xml
  - *.txt
  - feed.xml
  - Gemfile*
  - package*.json
  - README.md

comments:
  provider: false  # Set to disqus and add short_name if needed

nav:
  - PROJECTS: "/projects/"  
  - BLOG: "/blog/"
  - ABOUT ME: "/about/"

translations:
  permalink: "/404.html"

destination: ./_site
port: 4000

markdown: kramdown
highlighter: rouge
permalink: "/blog/:title/"
paginate: 6
paginate_path: "/blog/page:num/"
categories_path: "/blog/category/"
tags_path: "/blog/tag/"

plugins:
  - jekyll-paginate

exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md

sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
  include_posts:
    - "/writing/"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
