title: The Bandar Co.
email: "amaydeepp12510@gmail.com"
description: "B.Com Grad"
url: "https://thebandar.co.in"
baseurl: ""

owner:
  name: Amay
  avatar: avatar.png
  favicon: favicon.ico
  info: Portfolio, blog and more

whatsapp_number: "7588643764"
instagram_username: "chillbandar"
linkedin_username: "amay-deep-34158b229"
github_username: "XiaoPongo"

nav:
  - PROJECTS: "/projects/"
  - BLOG: "/blog/"
  - ABOUT ME: "/about/"

permalink: "/blog/:title/"
paginate: 6
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate

exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md

sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
  include_posts:
    - "/writing/"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
